server:
  port: 8082

spring:
  application:
    name: dataset-service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/insightflow}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max.block.ms: 3000 # Don't block startup or APIs if Kafka isn't up
