server:
  port: 4000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/auth/**

        - id: dataset-service
          uri: ${DATASET_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/dataset/**

        - id: analytics-service
          uri: ${ANALYTICS_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/analytics/**, /api/charts/**, /api/predictions/**, /api/chat/**
